---
title: "Cascade Impactor"
author: "Magali Blanco"
date: "1/18/2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

upload Eddie's datasheet
```{r}
MylarData <- read_excel("~/Everything/School/PhD_UW/Courses/2. Winter 18/ENVH 595 Yost RR/Data/Cascade Impactor/Eddie/MylarData.xls")

#only include relevant columns 
Mylar <- MylarData[c("sprayer", "collectdate", "samp_id", "height_m", "dist_m", "sampvol_l", "stage", "ug", "below_loq", "drift_ml", "conc_ml_l")] #ml drift vol / l vol sampled 

#convert "conc_ml_l" to "conc_ug_cm3"
## ml numerator to ug: * water density 1 g/ml * (10^6 ug/g) = ug/ml density
## l denominator to cm3: * (1 L / 10^3 cm3)
Mylar$conc_ug_cm3 <- Mylar$conc_ml_l*1*(10^6)/(10^3)

#relabel sprayers 
Mylar$sprayer <- ifelse(Mylar$sprayer=="pak", "AFA", ifelse(Mylar$sprayer=="quantum", "MFT", "turbo"))

#only use Sept 2016 values
Mylar <-Mylar[Mylar$collectdate >="2016-09-28" & Mylar$collectdate <="2016-09-30",]

#change date name
colnames(Mylar)[colnames(Mylar) =="collectdate"] <- "ObservedDate"

#add cutpoint associated with each stage
Mylar$cut_um <- ifelse(Mylar$stage==1, 21.3, ifelse(Mylar$stage==2, 14.8, ifelse(Mylar$stage==3, 9.8, ifelse(Mylar$stage==4, 6, ifelse(Mylar$stage==5, 3.5, ifelse(Mylar$stage==6, 1.55, ifelse(Mylar$stage==7, 0.93, ifelse(Mylar$stage==8, 0.52,0))))))))

#only keep locations collocated w/ Dylos



# only keep values above LOQ? 

# 

```



#TEST plots of AFA (n=48 stage samples)
-NOTE: uses all data. delete non-collocated locations, dates
-? do it by day??

what functions to use? 
geom_histogram, geom_freqpoly, stat_ecdf
```{r}
#histogram 
ggplot(data=Mylar[Mylar$sprayer=="AFA",], aes(x=conc_ug_cm3)) + geom_freqpoly() #geom_histogram()

#cumulative probability plot
ggplot(data=Mylar[Mylar$sprayer=="AFA",], aes(x=conc_ug_cm3)) + stat_ecdf() + labs(y="Cumulative Probability", x= "Concentration (ug/cm3)")



```

